# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HTRUC Catalog
on:
  push:
    branches:
      - master
  workflow_dispatch: #Allows for manual triggering
jobs:
  catalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install htruc==0.0.1
    - name: Run HTRUC
      run: |
        htruc make  ./catalog --access_token ${{ secrets. GITHUB_TOKEN }} --graph-csv data.csv --statistics statistics.csv --output htr-united.yml --graph graph.png --json catalog.json
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add htr-united.yml graph.png statistics.csv catalog.json
        git commit -m "[Automatic] Update of the Catalog" || echo "Nothing to commit"
        git push
    - uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
        use_github_release_notes: true
